S03 us04 page actualite visiteur
WildCodeSchool/orleans-php-202103-project-javoy pull request #110
Opened 2021-04-26 09:54 UTC by RedPandore

2021-04-27 09:10 UTC, sev-30 approved these changes

2021-04-27 11:43 UTC, endricklosange approved these changes

2021-04-27 13:22 UTC, sblondeau requested changes

2021-04-27 13:22 UTC, sblondeau commented on public/assets/css/style.css
> +@import "actuality.css";
non tu ne dois pas importer ton fichier actuality.css dans style.css car dans ce cas le style des actus sont chargés systématiquement pour toutes les pages. 
Au contraire, il faut ajouter dans un block stylesheet juste les feuilles de style nécessaire à chaque page, comme ça c'est moins lourd (#ecoconception :p )

2021-04-27 13:22 UTC, sblondeau commented on src/Controller/HomeController.php
> +    public function actuality(): string
j'aurais plutot tendance à créer une méthode index dans un ActualityController, je trouve que c'est plus "clair" pour s'y retrouver, meme si comme ça ça fonctionne aussi. Mais en tout cas c'est pas grave d'avoir un controlleur avec juste une seule méthode index().

2021-04-27 13:22 UTC, sblondeau commented on src/View/Home/actuality.html.twig
> +{% extends 'layout.html.twig' %}
et ici ça serait View/Actuality/index

2021-04-27 13:34 UTC, RedPandore commented on public/assets/css/style.css
> +@import "actuality.css";
Oui effectivement sa parait plus logique x)
A pour ma défence, le site est peut etre mal optimisé mais en contrepartie je recycle toujours mes appareils xD

2021-04-27 17:43 UTC, Serdar45000 approved these changes

2021-04-27 20:47 UTC, sev-30 approved these changes

2021-04-28 07:09 UTC, sblondeau approved these changes

2021-04-28 07:09 UTC, merged