S03 us05 ajout actu
WildCodeSchool/orleans-php-202103-project-javoy pull request #123
Opened 2021-04-27 20:54 UTC by endricklosange

2021-04-27 22:03 UTC, Valentin-int approved these changes

2021-04-28 08:49 UTC, sev-30 submitted a review, later dismissed

2021-04-28 08:55 UTC, Valentin-int submitted a review, later dismissed

2021-04-28 08:56 UTC, Serdar45000 approved these changes

2021-04-28 13:44 UTC, sblondeau requested changes

2021-04-28 13:44 UTC, sblondeau commented on src/Controller/AdminActualityController.php
> +    private const NEWS_MAX_LENGHT = 80;
LENGTH pas LENGHT

2021-04-28 13:44 UTC, sblondeau commented on src/Controller/AdminActualityController.php
> +                $errors[] = 'Le nom doit contenir moin de ' . self::DESCRIPTION_MAX_LENGHT . 'caractère';
idem, attention à l'ortho

2021-04-28 13:44 UTC, sblondeau commented on src/Controller/AdminActualityController.php
> +                $errors[] = 'Le nom doit contenir moin de ' . self::NEWS_MAX_LENGHT . 'caractère';
moin**s**
caractère**s**

2021-04-28 13:44 UTC, sblondeau commented on src/Controller/AdminActualityController.php
> +    private const DESCRIPTION_MAX_LENGHT = 500;
le max length sur la description est pas forcément nécessaire, je te laisse voir si c'est pertinent

2021-04-28 14:31 UTC, Valentin-int submitted a review, later dismissed

2021-04-28 18:00 UTC, RedPandore requested changes
Juste le bouton à renommé

2021-04-29 06:34 UTC, RedPandore approved these changes

2021-04-29 08:08 UTC, Valentin-int approved these changes

2021-04-29 08:18 UTC, RedPandore approved these changes

2021-04-29 09:25 UTC, sblondeau approved these changes

2021-04-29 09:25 UTC, merged