S03 us01 contact plan et horaires
WildCodeSchool/orleans-php-202103-project-javoy pull request #127
Opened 2021-04-28 10:09 UTC by sev-30

2021-04-28 10:15 UTC, endricklosange submitted a review, later dismissed

2021-04-28 10:19 UTC, Valentin-int submitted a review, later dismissed

2021-04-28 14:43 UTC, sblondeau requested changes

2021-04-28 14:43 UTC, sblondeau commented on src/View/Contact/index.html.twig
> +        var places = {
utilise const ou let, mais pas de var
const => si tu n'as pas à changer la valeur de ta variable (pas de reaffectation), sinon let
sauf erreur de ma part tu devrais pouvoir mettre un const à la place de tes différents var, mais si ça te sort une erreur, passe en let :p

2021-04-28 14:43 UTC, sblondeau commented on src/View/Contact/index.html.twig
> +        var carte = L.map('maCarte').setView([47.83309, 1.81769], 11);
idem

2021-04-28 14:43 UTC, sblondeau commented on src/View/Contact/index.html.twig
> +    <script>
cree un fichier map.js, mets le code dedans et ta balise script te permettra de chargher ce fichier

2021-04-29 08:37 UTC, Valentin-int submitted a review, later dismissed

2021-04-29 11:45 UTC, RedPandore approved these changes

2021-04-29 13:10 UTC, Valentin-int approved these changes

2021-04-29 13:26 UTC, Valentin-int approved these changes

2021-04-29 14:02 UTC, RedPandore approved these changes

2021-04-29 15:40 UTC, sblondeau approved these changes

2021-04-29 15:40 UTC, merged