S03 us02 form contact
WildCodeSchool/orleans-php-202103-project-javoy pull request #128
Opened 2021-04-28 10:16 UTC by Valentin-int

2021-04-28 10:26 UTC, sev-30 submitted a review, later dismissed

2021-04-28 11:32 UTC, RedPandore submitted a review, later dismissed

2021-04-28 13:54 UTC, sblondeau requested changes

2021-04-28 13:54 UTC, sblondeau commented on public/assets/css/contact.css
> +    background-color: #493131;
couleur en variable CSS

2021-04-28 13:54 UTC, sblondeau commented on src/Controller/ContactController.php
> +    private const NAME_MAX_LENGHT = 80;
mets les constantes en début de classe c'est plus lisible, sinon on les voit pas bien au milieu des méthodes

2021-04-28 13:54 UTC, sblondeau commented on src/Controller/ContactController.php
> +    private const NAME_MAX_LENGHT = 80;
et LENGTH par LENGHT

2021-04-28 13:54 UTC, sblondeau commented on src/Controller/ContactController.php
> +            $errors = 'Le message doit faire moin de ' . self::MESSAGE_MAX_LENGHT . ' caractères';
moin**s**

2021-04-28 14:54 UTC, endricklosange approved these changes

2021-04-29 08:15 UTC, RedPandore approved these changes

2021-04-29 09:26 UTC, sblondeau approved these changes

2021-04-29 09:26 UTC, merged