initialisation
WildCodeSchool/orleans-php-202103-project-javoy pull request #17
Opened 2021-04-09 15:04 UTC by endricklosange

2021-04-09 15:12 UTC, RedPandore approved these changes

2021-04-09 19:45 UTC, Serdar45000 submitted a review, later dismissed

2021-04-12 06:59 UTC, sblondeau requested changes

2021-04-12 06:59 UTC, sblondeau commented on src/View/layout.html.twig
> +    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js%22%3E</script>
non jquery est plus nécessaire dans bootstrap depuis la V5

2021-04-12 08:27 UTC, Serdar45000 approved these changes

2021-04-12 08:29 UTC, Serdar45000 approved these changes

2021-04-12 08:29 UTC, Serdar45000 approved these changes

2021-04-12 13:33 UTC, Serdar45000 approved these changes

2021-04-12 13:36 UTC, Serdar45000 approved these changes

2021-04-12 13:55 UTC, Serdar45000 approved these changes

2021-04-12 13:57 UTC, sblondeau requested changes

2021-04-12 13:57 UTC, sblondeau commented on src/View/layout.html.twig
>      {% block javascript %}{% endblock %}
le block javascript doit etre appelé en dessous de ta balises script, sinon tu ne pourras pas surchargé le js de bootstrap

2021-04-12 15:14 UTC, sblondeau approved these changes

2021-04-12 15:14 UTC, merged