S04 us14 us15 us17 order
WildCodeSchool/orleans-php-202103-project-javoy pull request #177
Opened 2021-05-03 13:55 UTC by Serdar45000

2021-05-04 07:22 UTC, RedPandore approved these changes

2021-05-04 08:25 UTC, endricklosange submitted a review, later dismissed

2021-05-04 08:53 UTC, sblondeau requested changes

2021-05-04 08:53 UTC, sblondeau commented on src/Model/AdminOrderManager.php
> +        $query = 'SELECT'  .  static::TABLE . '.id, '  .  static::TABLE . '.title,'
pas besoni de préfixer chaque champ avec le nom de la table
tu mes plutot un alias à ton nom de table si nécessaire

De plus, ton manager devrait s'appeler OrderManager et non AdminOrderManager

2021-05-04 08:53 UTC, sblondeau commented on src/Controller/AdminOrderController.php
> +            $statusOrder->update($orderStatus);
la méthode devrai plutot s'appeler update() que show() non ? si le but est de mettre à jour l'order ?

2021-05-04 14:29 UTC, endricklosange approved these changes

2021-05-05 07:55 UTC, RedPandore approved these changes

2021-05-05 07:59 UTC, sblondeau approved these changes

2021-05-05 07:59 UTC, merged