HTML form ajout de produit Admin
WildCodeSchool/orleans-php-202103-project-javoy pull request #18
Opened 2021-04-14 08:51 UTC by RedPandore

2021-04-14 08:55 UTC, endricklosange submitted a review, later dismissed

2021-04-14 08:55 UTC, Valentin-int approved these changes

2021-04-15 11:51 UTC, sblondeau requested changes

2021-04-15 11:51 UTC, sblondeau commented on src/Controller/AdminController.php
> +class AdminController extends AbstractController
Cette classe gère les boissons, donc je l'appelerais plutot AdminDrinkController ou AdminProductController non ?
tu peux avoir un AdminController qui gérera la page d'accueil de la partie admin

2021-04-15 11:51 UTC, sblondeau commented on src/Controller/AdminController.php
> +    public function index()
cette méthode sera pour l'US : lister les boissons coté admin, enlève la pour le moment. Il ne faut mettre que du code propre à ta US

2021-04-15 11:51 UTC, sblondeau commented on src/View/Admin/_adminForm.html.twig
> +      <option selected>Catégorie</option>
cette option ne sert à rien pour moi, le label se suffit à lui meme

2021-04-15 11:51 UTC, sblondeau commented on src/View/Admin/_adminForm.html.twig
> +      <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="Nom du produit" value="nom" required>
les placeholder ne doivent pas reprendre le label, il faut que ce soit un exemple, placeholder="Jus de raisin", modifie les tous

2021-04-15 13:51 UTC, endricklosange approved these changes

2021-04-15 13:56 UTC, sev-30 submitted a review, later dismissed

2021-04-15 14:01 UTC, Serdar45000 submitted a review, later dismissed

2021-04-15 14:22 UTC, Serdar45000 submitted a review, later dismissed

2021-04-15 14:24 UTC, endricklosange submitted a review, later dismissed

2021-04-15 15:17 UTC, sblondeau requested changes

2021-04-15 15:17 UTC, sblondeau commented on src/Controller/AdminProductsController.php
> +        $categoryValue = array("Rouge", "Blanc", "Rosé", "Alcool de fruit", "Jus de fruit"); // category list
[] et pas array()

2021-04-15 15:17 UTC, sblondeau commented on src/Model/ProductsManager.php
> +class ProductsManager extends AbstractManager
product et pas product
les tables sont tjs au singulier ! => renomme tout, sorry (table, controleur etc)

2021-04-15 15:17 UTC, sblondeau commented on src/View/Admin/_adminProductsForm.html.twig
> +    <select class="form-select mb-3" aria-label="Default select example" value= "{{ products.category }}" name="category" required>
idealement tu devrais gérer
- une US pour le form sans les catégories
- une US pour ajouter la notion de catégories (comme j'ai fais pour le LC)
car là en l'état à un moment donné tu vas devoir ajouter une table category et donc ces infos viendront de la bdd (avec une requete, une boucle etc) et tu devras refaire toute la partie HTML et la validation pour les categ). Mais bon, laisse comme ça pour le moment, tant pis je vais pas tout te faire refaire

2021-04-15 15:17 UTC, sblondeau commented on src/Controller/AdminProductsController.php
> +            $errors[] = 'Le nom doit contenir moin de 80 charactères';
moin**s**

et utilise des constantes plutot pour ces valeurs limites const PRODUCT_MAX_LENGHT = 80 et tu reutilises cette constante dans la condition ET dans le message d'erreur. Idem plus bas avec le 255

2021-04-15 15:17 UTC, sblondeau commented on src/Controller/AdminProductsController.php
> +            $errors[] = 'Veuillez renseigné une catégorie valide';
renseigner

2021-04-15 15:17 UTC, sblondeau commented on src/Controller/AdminProductsController.php
> +            $errors[] = 'Le prix doit etre un nombre supérieur a 0';
**à** (à corriger partout)

2021-04-15 15:50 UTC, RedPandore commented on src/View/Admin/_adminProductsForm.html.twig
> +    <select class="form-select mb-3" aria-label="Default select example" value= "{{ products.category }}" name="category" required>
Ah oui effectivement je n'avais pas pensé a sa. Merci

2021-04-15 15:53 UTC, RedPandore commented on src/Model/ProductsManager.php
> +class ProductsManager extends AbstractManager
Pas de problème c'est comme sa qu'on apprend ;D

2021-04-15 16:33 UTC, endricklosange approved these changes

2021-04-15 22:19 UTC, Serdar45000 approved these changes

2021-04-16 06:55 UTC, sblondeau approved these changes

2021-04-16 06:55 UTC, merged