Update index admin
WildCodeSchool/orleans-php-202103-project-javoy pull request #19
Opened 2021-04-14 09:19 UTC by Valentin-int

2021-04-14 09:21 UTC, RedPandore requested changes
Il manque des lignes vides en fin de fichier, sur le manager et sur le layout_admin

2021-04-14 14:16 UTC, endricklosange approved these changes
comme Tennessee les 2 espace sinon c'est ok

2021-04-15 10:16 UTC, RedPandore approved these changes

2021-04-15 11:55 UTC, sblondeau requested changes

2021-04-15 11:55 UTC, sblondeau commented on src/View/Admin/add-products.html.twig
> +{% extends 'layout_admin.html.twig' %}
cette page n'a rien à faire dans ta PR, ce n'est pas ton US

2021-04-15 11:55 UTC, sblondeau commented on src/View/Admin/index.html.twig
> +<h1>Partie Admin</h1>
c'est tout ce que tu y fais? pas de mise en page du tout ? c'est une partie admin, pas besoin de fioriture, mais si c'est juste pour afficher un h1 autant pas faire la page ^^
sinon mettez au moins un paragraphe " Cette partie réservée à l'administrateur vous permettra de gérer votre site" et une image pour faire accueillant :D

2021-04-15 12:53 UTC, closed without merging