S01 us12 header
WildCodeSchool/orleans-php-202103-project-javoy pull request #21
Opened 2021-04-14 11:47 UTC by endricklosange

2021-04-14 13:10 UTC, RedPandore submitted a review, later dismissed

2021-04-14 13:45 UTC, Serdar45000 submitted a review, later dismissed

2021-04-14 15:14 UTC, sblondeau requested changes

2021-04-14 15:14 UTC, sblondeau commented on public/assets/css/header.css
> +.logo{
avec la grid de bootstrap et les flexbox, tu ne devrais avoir besoin ni du float right, ni des media queries

2021-04-14 15:14 UTC, sblondeau commented on public/assets/css/style.css
>      --primary:#ffffff;
ton primary doit etre ta couleur principale, donc ton rouge vin (mais pour le blanc cree plutot un --light)

2021-04-14 15:14 UTC, sblondeau commented on src/View/includes/_navbar.html.twig
> +  <a class="navbar-brand" href="#">Acceuil</a>
tu peux déjà mettre un lien vers "/" pour revenir vers l'acc**u**eil, mais n'écrit pas Accueil, mais plus "Javoy"

2021-04-15 07:23 UTC, sev-30 submitted a review, later dismissed

2021-04-15 07:23 UTC, Serdar45000 submitted a review, later dismissed

2021-04-15 09:05 UTC, sblondeau requested changes

2021-04-15 09:05 UTC, sblondeau commented on public/assets/css/header.css
> +@media screen and (max-width: 768px)
tjs inutile cette media query
regarde bien au niveau des classes de bootstrap, tu as d-xx-none ou d-xx-flex, d-xx-block (avec xx la taille) qui permet de cacher/afficher des élémenst à partir d'une taille précise et ça t'évite la metdia query. 
Mais au dela de ça, cacher le logo sur petit écran je sais pas si c'est une bonne idée?

2021-04-15 13:50 UTC, RedPandore approved these changes

2021-04-15 13:58 UTC, sev-30 approved these changes

2021-04-15 15:19 UTC, sblondeau approved these changes

2021-04-15 15:19 UTC, merged