création page produit
WildCodeSchool/orleans-php-202103-project-javoy pull request #27
Opened 2021-04-15 21:10 UTC by sev-30

2021-04-15 21:11 UTC, Serdar45000 submitted a review, later dismissed

2021-04-15 21:12 UTC, endricklosange approved these changes

2021-04-16 06:54 UTC, sblondeau commented
Ca ne passe pas les check de githubAction (d'où la croix rouge à coté du nom de la PR) 
Je ne relis pas tant que ça ne passe pas ;-)

2021-04-16 07:36 UTC, Serdar45000 approved these changes

2021-04-16 07:36 UTC, RedPandore approved these changes

2021-04-16 08:10 UTC, sblondeau requested changes
les images doivent faire moins de 200ko  comme je vous l'ai dis dans le LC.
là elle font toutes pres de 800ko ce qui est bien trop lourd

2021-04-21 14:29 UTC, closed without merging