S02 us06 footer
WildCodeSchool/orleans-php-202103-project-javoy pull request #57
Opened 2021-04-20 07:59 UTC by RedPandore

2021-04-20 08:17 UTC, Serdar45000 submitted a review, later dismissed

2021-04-20 15:15 UTC, sblondeau requested changes
pour les images de logo de reseaux sociaux, si possible utilises plutot des icones en svg (par ex https://icons.getbootstrap.com/icons/facebook/) c'est BEAUCOUP plus léger ;-)

2021-04-20 15:15 UTC, sblondeau commented on public/assets/css/footer.css
> +    background: #292929;
couleur en variable

2021-04-20 15:15 UTC, sblondeau commented on public/assets/css/footer.css
> +    font-family: 'Playfair Display', serif;
font en variable

2021-04-20 15:15 UTC, sblondeau commented on public/assets/css/footer.css
> +    color: grey;
varialbe

2021-04-20 15:15 UTC, sblondeau commented on public/assets/css/footer.css
> +    color: #f5f5f5 !important;
variable ET jamais en !important, c'est une mauvaise pratique

je vois qu'il y a d'autres couleurs pas en variable un peu partout, je te laisse tout corriger

2021-04-20 15:15 UTC, sblondeau commented on src/View/Admin/add.html.twig
>              </div>
ce fichier ne devrait pas etre add dans la PR

2021-04-21 09:02 UTC, Serdar45000 approved these changes

2021-04-21 09:04 UTC, endricklosange approved these changes

2021-04-21 09:05 UTC, Valentin-int approved these changes

2021-04-21 13:40 UTC, sblondeau approved these changes

2021-04-21 13:40 UTC, merged