S02 us07 fonction delete  produit admin
WildCodeSchool/orleans-php-202103-project-javoy pull request #59
Opened 2021-04-21 09:46 UTC by Valentin-int

2021-04-21 10:01 UTC, RedPandore submitted a review, later dismissed

2021-04-21 14:52 UTC, sblondeau requested changes

2021-04-21 14:52 UTC, sblondeau commented on src/Controller/AdminProductController.php
> +    public function delete(int $id): void
manque pas la partie vue ? avec le form de delete en HTML

2021-04-23 00:56 UTC, Serdar45000 approved these changes

2021-04-27 22:58 UTC, Serdar45000 reviewed
Il faut sérieusement changer le deleteBnt... delete-btn ou deleteBtn !

2021-04-28 11:26 UTC, endricklosange approved these changes

2021-04-28 13:41 UTC, sblondeau approved these changes

2021-04-28 13:41 UTC, merged