S02 us09 creation formulaire commande
WildCodeSchool/orleans-php-202103-project-javoy pull request #70
Opened 2021-04-22 08:54 UTC by Serdar45000

2021-04-22 10:00 UTC, sev-30 commented
dans javoydb.sql 
CREATE table product apparait en commentaire et tu as seulement dedans
  created_at DATE NOT NULL
);
c'est normal ?

2021-04-22 13:11 UTC, sev-30 approved these changes

2021-04-22 13:12 UTC, sev-30 submitted a review, later dismissed

2021-04-22 13:40 UTC, sev-30 approved these changes

2021-04-22 14:28 UTC, sblondeau requested changes
le fichier db.php.dist ne doit pas etre supprimé (c'est un "modèle" pour les personnes qui récupères le projet)

2021-04-22 14:28 UTC, sblondeau commented on src/View/includes/_orderForm.html.twig
> +
affiche les erreurs avant le form plutot

2021-04-22 14:28 UTC, sblondeau commented on src/View/Item/index.html.twig
> +  </div>
tu n'as pas à toucher à cette page, le dossier Item c'est pour l'exemple, ça n'a rien à faire dans cette PR
si c'est pour les product, ça devrait etre dans un dossier Product et pa Item, mais dans tous les cas c'est pas cette US qui s'occupe de ça

2021-04-22 14:28 UTC, sblondeau commented on src/Controller/OrderController.php
> +    {
manque toutes les verifications coté serveur et l'insert en BDD si pas d'erreur

2021-04-23 07:22 UTC, RedPandore submitted a review, later dismissed

2021-04-23 07:27 UTC, sev-30 submitted a review, later dismissed

2021-04-23 07:50 UTC, sblondeau requested changes

2021-04-23 07:50 UTC, sblondeau commented on JavoyDb.sql
> +CREATE TABLE orders (
order  au singulier

2021-04-23 07:50 UTC, sblondeau commented on public/assets/css/order.css
> +h1{
beaucoup de ces styles (h1, form, button, label, etc) sont je pense des styles généraux à votre site (pas de raison qu'ils soient juste propre à cette page d'order) donc devrait etre mis dans style.css

par contre des trucs comme .order{ .... } qui sont vraiment propre à la page ça reste là, il faut faire le tri et se mettre d'accord sur les styles, et se reposer aussi un max sur bootstrap (par ex surcharger form ou label me parait pas une bonne solution)

2021-04-23 07:50 UTC, sblondeau commented on src/Controller/OrderController.php
> +        $error = [];
$errors (c'est un tableau contenant plusieurs erreurs)

2021-04-23 07:50 UTC, sblondeau commented on src/Controller/OrderController.php
> +        $error = $this->isEmpty($order);
$errors

2021-04-23 07:50 UTC, sblondeau commented on src/Model/OrderManager.php
> +    public const TABLE = 'orders';
order

2021-04-23 07:50 UTC, sblondeau commented on src/Controller/OrderController.php
> +        $error = [];
errors

2021-04-23 07:50 UTC, sblondeau commented on src/Controller/OrderController.php
> +            'error' => $error,
error**s** (tu envois d'ailleurs 'error' mais coté twig tu essaies de boucler sur 'errors' avec un S qui n'existe donc pas !

2021-04-23 07:50 UTC, sblondeau commented on src/View/includes/_orderForm.html.twig
> +{% if errors is empty  %}
plutot qu'un if vide je crois que tu peux faire {% if errors is not emtpy %}

2021-04-26 07:49 UTC, sev-30 approved these changes

2021-04-26 08:54 UTC, Valentin-int approved these changes

2021-04-26 09:03 UTC, sblondeau approved these changes

2021-04-26 09:03 UTC, merged