S02 us3 category index
WildCodeSchool/orleans-php-202103-project-javoy pull request #71
Opened 2021-04-22 09:21 UTC by sev-30

2021-04-22 09:55 UTC, Valentin-int submitted a review, later dismissed

2021-04-22 12:53 UTC, Valentin-int submitted a review, later dismissed

2021-04-22 13:25 UTC, RedPandore approved these changes

2021-04-22 13:30 UTC, endricklosange approved these changes

2021-04-22 13:30 UTC, Valentin-int approved these changes

2021-04-22 14:43 UTC, sblondeau requested changes

2021-04-22 14:43 UTC, sblondeau commented on public/assets/css/category.css
> +*{padding:0px;
évite ce genre de chose, là tu reset le padding et margin de tous les éléments, or bootstrap a déjà ses propres espacements et ça peut te jouer des tours je pense

2021-04-22 14:43 UTC, sblondeau commented on src/Model/CategoryManager.php
> +        $categoryManager = new CategoryManager();
non ! là tu instancie l'objet CategoryManager à l'intérieur de lui meme ! ta classe étend AbstractManager, donc tu as déjà accès au méthodes de AbstractManager sans rien faire.

donc pas besoin de créer ce listCategory(), d'autant qu'au final tu ne t'en sers pas dans ton controller et  tu utilises bien selectAll directement

2021-04-23 00:53 UTC, Serdar45000 approved these changes

2021-04-29 13:34 UTC, closed without merging

2021-04-29 13:35 UTC, sev-30 commented
plus besoin