Fix ajout des images de récompense
WildCodeSchool/orleans-php-202103-project-javoy pull request #83
Opened 2021-04-23 07:41 UTC by Valentin-int

2021-04-23 07:42 UTC, RedPandore approved these changes

2021-04-23 07:51 UTC, RedPandore requested changes

2021-04-23 07:51 UTC, RedPandore commented on src/View/includes/_recompense.html.twig
> +                <img class="card-img-top" src="../assets/images/medaille-or.png" alt="Médaille d'or">
Le lien vers l'image doit etre dans ce format : "/assets/images/medaille-or.png"
Sans les ...

2021-04-23 13:17 UTC, Serdar45000 approved these changes

2021-04-23 14:54 UTC, sev-30 approved these changes

2021-04-26 07:15 UTC, sblondeau approved these changes

2021-04-26 07:16 UTC, merged